[package]
name = "mc-constant-time-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subtle = "2.4"
rand_core = { version = "0.6", default-features = false }
rand_hc = "0.3"
